### ISSUE TITLE
What are the corelation and causation IDs for?

### ISSUE THREAD

**Issue by kudapara** [thenativeweb/commands-events#1]
I am wondering what the correlation and causation ids are in the meta data for the events. I am new to this concept of DDD and event sourcing, so explaining what they are and what purpose they serve a little bit further would be helpful.

Are these IDs supposed to be random? How are they generated? When I exclude them an exception is raised. Please do help.

**Comment by goloroden** [comment]
Actually, there are three IDs:

- The command / event ID itself.
- The causation ID.
- The correlation ID.

Their meaning is as follows:

The ID is just an identifier for a single command / event. We've decided to use a UUID for this, so that clients can also generate them, without the need for a central ID management solution, such as a database. It's just an ID.

Now, command typically leads to events. In other words: Events are *caused* by commands. This is what causation IDs are for: They create a link between a command and an event, where one led to the other. While an event gets its own ID, its causation ID is set to the ID of the command that the event responds to. If commands are being created as a result of an event, they can have a causation ID as well. In these terms, causation IDs define 1:1 relations between commands and events.

Now you may have a chain, i.e.: A command that causes an event, that again causes a command, that causes an event, and so on… Each of them has their own unique and independent ID, and each two of them are connected by a causation ID: You could use the causation ID of the last one to step backwards to the chain and find the predecessor of each element. Anyway, it is difficult to get all the commands and events at once that belong to a chain. This is what the correlation ID is for: It is set to the ID of the very first command, and then copied over when the command causes an event, or an event causes a command.

So, to cut a long story short:

- ID: Identifier of a single command / event.
- Causation ID: Pointer to the predecessor of a command / event.
- Correlation ID: Pointer to the first command / event in a chain to identify a long-running transaction.

Hope this helps 😊

**Comment by kudapara** [comment]
Thank you very much @goloroden for an excellent explanation :clap: :clap:  

As a suggestion, if you could put together a tutorial/blog post explaining how all works (maybe in the context of a real world app) I think you might help a lot of people.

**Comment by goloroden** [comment]
Thanks a lot for your very nice feedback 😊 

And putting together a blog post is a great idea, thanks for that 👍 
I'll put that on my todo list, and let you know once it's done (but this may take a while…).

**Comment by kudapara** [comment]
Thank you once again. You are a pleasure to work with.

**Comment by goloroden** [comment]
@kudapara FYI: We have turned this into a blog post, which will go live on June 5th. Watch out https://www.thenativeweb.io/blog … 😊
